-- Meetwell database setup for Supabase.
-- 1. Run this entire file once in Supabase > SQL Editor.
-- 2. In Authentication > Providers, enable Anonymous Sign-Ins.
-- The configured admin password is stored below only as a bcrypt hash.

create extension if not exists pgcrypto;

create table if not exists public.settings (
  id text primary key,
  title text not null check (char_length(title) between 1 and 80),
  start_date date not null,
  end_date date not null,
  default_view text not null default 'month' check (default_view in ('week', 'two-week', 'month')),
  updated_at timestamptz not null default now(),
  constraint valid_date_range check (end_date >= start_date)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_secrets (
  id smallint primary key check (id = 1),
  password_hash text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  expires_at timestamptz not null
);

create table if not exists public.availability (
  settings_id text not null references public.settings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  available_date date not null,
  display_name text not null check (char_length(display_name) between 1 and 40),
  created_at timestamptz not null default now(),
  primary key (settings_id, user_id, available_date)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  settings_id text not null references public.settings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  body text not null check (char_length(body) between 1 and 600),
  created_at timestamptz not null default now()
);

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  settings_id text not null references public.settings(id) on delete cascade,
  added_by uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  name text not null check (char_length(name) between 1 and 80),
  note text not null default '' check (char_length(note) <= 140),
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  settings_id text not null references public.settings(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (restaurant_id, user_id)
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1
    from public.admin_sessions
    where user_id = auth.uid()
      and expires_at > now()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.unlock_admin(input_password text)
returns boolean
language plpgsql
volatile
security definer
set search_path = public, extensions
as $$
declare
  stored_hash text;
begin
  if input_password is null or char_length(input_password) > 128 then
    return false;
  end if;

  select password_hash into stored_hash
  from public.admin_secrets
  where id = 1;

  if stored_hash is null or crypt(input_password, stored_hash) <> stored_hash then
    return false;
  end if;

  insert into public.admin_sessions (user_id, expires_at)
  values (auth.uid(), now() + interval '12 hours')
  on conflict (user_id) do update
  set expires_at = excluded.expires_at;

  return true;
end;
$$;

revoke all on function public.unlock_admin(text) from public;
grant execute on function public.unlock_admin(text) to authenticated;

-- Run this only from the Supabase SQL Editor to set or rotate the password.
-- Do not grant it to anonymous or authenticated browser users.
create or replace function public.set_admin_password(input_password text)
returns void
language plpgsql
volatile
security definer
set search_path = public, extensions
as $$
begin
  if input_password is null or char_length(input_password) < 6 or char_length(input_password) > 128 then
    raise exception 'Admin password must be between 6 and 128 characters.';
  end if;

  insert into public.admin_secrets (id, password_hash, updated_at)
  values (1, crypt(input_password, gen_salt('bf', 12)), now())
  on conflict (id) do update
  set password_hash = excluded.password_hash,
      updated_at = excluded.updated_at;

  delete from public.admin_sessions;
end;
$$;

revoke all on function public.set_admin_password(text) from public;
grant execute on function public.set_admin_password(text) to service_role;

alter table public.settings enable row level security;
alter table public.profiles enable row level security;
alter table public.admin_secrets enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.availability enable row level security;
alter table public.messages enable row level security;
alter table public.restaurants enable row level security;
alter table public.votes enable row level security;

drop policy if exists "settings readable" on public.settings;
create policy "settings readable" on public.settings for select to authenticated using (true);
drop policy if exists "admins update settings" on public.settings;
create policy "admins update settings" on public.settings for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select to authenticated using (true);
drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "availability readable" on public.availability;
create policy "availability readable" on public.availability for select to authenticated using (true);
drop policy if exists "users add own availability" on public.availability;
create policy "users add own availability" on public.availability for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "users update own availability" on public.availability;
create policy "users update own availability" on public.availability for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users remove own availability" on public.availability;
create policy "users remove own availability" on public.availability for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "messages readable" on public.messages;
create policy "messages readable" on public.messages for select to authenticated using (true);
drop policy if exists "users add messages" on public.messages;
create policy "users add messages" on public.messages for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "restaurants readable" on public.restaurants;
create policy "restaurants readable" on public.restaurants for select to authenticated using (true);
drop policy if exists "users add restaurants" on public.restaurants;
create policy "users add restaurants" on public.restaurants for insert to authenticated with check (auth.uid() = added_by);
drop policy if exists "admins update restaurants" on public.restaurants;
create policy "admins update restaurants" on public.restaurants for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins remove restaurants" on public.restaurants;
create policy "admins remove restaurants" on public.restaurants for delete to authenticated using (public.is_admin());

drop policy if exists "votes readable" on public.votes;
create policy "votes readable" on public.votes for select to authenticated using (true);
drop policy if exists "users add own votes" on public.votes;
create policy "users add own votes" on public.votes for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "users remove own votes" on public.votes;
create policy "users remove own votes" on public.votes for delete to authenticated using (auth.uid() = user_id);

insert into public.settings (id, title, start_date, end_date, default_view)
values ('main', 'Next meetup', current_date + 1, current_date + 42, 'month')
on conflict (id) do nothing;

-- Realtime updates for everyone currently viewing the planner.
do $$
begin
  begin alter publication supabase_realtime add table public.settings; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.availability; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.restaurants; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.votes; exception when duplicate_object then null; end;
end $$;
